### ISSUE TITLE
Reading from standard input

### ISSUE THREAD

**Issue by grylem** [esselfe/texmex#2]
Please add the ability to read from standard input.
Thanks.

**Comment by esselfe** [comment]
Well my functions work with an option argument (optarg), I'll try reading more on detecting data on the stdin stream and add some conditional in the program option processing block...

Sorry for the response delay :P I don't check all my repos all the time ;)

**Comment by esselfe** [comment]
Thanks for the idea, closing with 43e710eb1a8bc4bb137f5776ba7176c188eafe09 and bfe1614930116e8927de6fa3cf04e4b436735392 .
